### ISSUE TITLE
Why do http:// URLs work in the popup but not in the main window?

### ISSUE THREAD

**Issue by waldenn** [vladimyr/radiocloud#48]
Hi Dario,

I'm trying to integrate your stream app into my own app, it all works nicely, except for one 'issue':
When I open this [link](https://conze.pt/explore/Amsterdam?l=en&t=radio-tags&p=1&s=true&i=727) eg., the "Amsterdam Funk Channel" stream won't play due to being blocked (due to using http:// instead of https://, ... a standard mixed content problem). **_However_** when I click the popup link, that same stream will play fine. Why is that?

I will probably have to try and open the plyr popup right away, but I'm not yet sure how to do that. Still, I'm very curious why the popup does work (tested on Firefox and Chrome).

Thanks for the nice radio-streaming app. Great minimal interface!

**Comment by waldenn** [comment]
Ok, I figured it out, I had an "upgrade-insecure-requests" CSP header on the mainpage, which was missing in the popup.

**Comment by vladimyr** [comment]
Thanks for the kind words. Great, I did a quick look, figured it is not CORS issue but failed to identify the actual cause. Also, keep in mind that you probably want to remove all Croatian stations from your bundle/player instance 😉

**Comment by ilijaveselica** [comment]
@vladimyr Maybe Croatian stations are more popular than you think 🤣

**Comment by vladimyr** [comment]
Moguće 😉
